### ISSUE TITLE
System Messages inconsistency.

### ISSUE THREAD

**Issue by artsiomrusak** [microsoftgraph/microsoft-graph-docs-contrib#1979]
Hello

I'm using this documentation to subscribe to system messages from `Teams` using `Graph API` - [https://docs.microsoft.com/en-us/graph/system-messages](https://docs.microsoft.com/en-us/graph/system-messages).

There is a list of system messages and places (chats, channels, etc.) where those events might be raised - [https://docs.microsoft.com/en-us/graph/system-messages](https://docs.microsoft.com/en-us/graph/system-messages).

Unfortunately, there are several issues:
1.  I can't get `callStartedEventMessageDetail` in 1-1 chat. **Could you please provide any info how this system event could be retrieved in 1-1 chat?**
2. Once I'm in a group chat I'm able to retrieve the `callStartedEventMessageDetail` and `callEndedEventMessageDetail`, but the json schema defined for those contracts is a little bit different.
For example I retrieved those system messages while doing a call in a group chat:
<details><summary>callStartedEventMessageDetail (please, expand to see the details)</summary>
<p>

```yaml
{
  "@odata.context": "https://graph.microsoft.com/$metadata#chats('19%3A16974b929af840df8dbce14a11064be4%40thread.v2')/messages/$entity",
  "id": "1657661644786",
  "replyToId": null,
  "etag": "1657661644786",
  "messageType": "unknownFutureValue",
  "createdDateTime": "2022-07-12T21:34:04.786Z",
  "lastModifiedDateTime": "2022-07-12T21:34:04.786Z",
  "lastEditedDateTime": null,
  "deletedDateTime": null,
  "subject": null,
  "summary": null,
  "chatId": "19:16974b929af840df8dbce14a11064be4@thread.v2",
  "importance": "normal",
  "locale": "en-us",
  "webUrl": null,
  "from": null,
  "body": {
    "contentType": "html",
    "content": "<systemEventMessage/>"
  },
  "channelIdentity": null,
  "attachments": [],
  "mentions": [],
  "onBehalfOf": null,
  "policyViolation": null,
  "reactions": [],
  "replies": [],
  "hostedContents": [],
  "eventDetail": {
    "@odata.type": "#Microsoft.Teams.GraphSvc.callStartedEventMessageDetail",
    "callId": null,
    "callEventType": "call",
    "initiator": {
      "application": null,
      "device": null,
      "user": {
        "userIdentityType": "aadUser",
        "id": "0845dc5e-73bc-4730-9e98-02626f220b6b",
        "displayName": null
      }
    }
  }
}
```

</p>
</details>

<details><summary>callEndedEventMessageDetail (please, expand to see the details)</summary>
<p>

```yaml
{
  "@odata.context": "https://graph.microsoft.com/$metadata#chats('19%3A16974b929af840df8dbce14a11064be4%40thread.v2')/messages/$entity",
  "id": "1657661676357",
  "replyToId": null,
  "etag": "1657661676357",
  "messageType": "unknownFutureValue",
  "createdDateTime": "2022-07-12T21:34:36.357Z",
  "lastModifiedDateTime": "2022-07-12T21:34:36.357Z",
  "lastEditedDateTime": null,
  "deletedDateTime": null,
  "subject": null,
  "summary": null,
  "chatId": "19:16974b929af840df8dbce14a11064be4@thread.v2",
  "importance": "normal",
  "locale": "en-us",
  "webUrl": null,
  "from": null,
  "body": {
    "contentType": "html",
    "content": "<systemEventMessage/>"
  },
  "channelIdentity": null,
  "attachments": [],
  "mentions": [],
  "onBehalfOf": null,
  "policyViolation": null,
  "reactions": [],
  "replies": [],
  "hostedContents": [],
  "eventDetail": {
    "@odata.type": "#Microsoft.Teams.GraphSvc.callEndedEventMessageDetail",
    "callId": null,
    "callDuration": "PT33S",
    "callEventType": "call",
    "callParticipants": [
      {
        "participant": {
          "application": null,
          "device": null,
          "user": {
            "userIdentityType": "aadUser",
            "id": "0845dc5e-73bc-4730-9e98-02626f220b6b",
            "displayName": "Artem Rusak"
          }
        }
      }
    ],
    "initiator": {
      "application": null,
      "device": null,
      "user": {
        "userIdentityType": "aadUser",
        "id": "0845dc5e-73bc-4730-9e98-02626f220b6b",
        "displayName": null
      }
    }
  }
}
```

</p>
</details>

Based on documentation I don't expect to have messageType as `unknownFutureValue`.
I'm subscribing to those events to acquire the `callId` value, but the `callId` value for _Call Started_ and _Call ended_ events is `null` _**which makes those system events absolutely useless**_.

**Could you please suggest whether it's an issue on Graph API side or I did smth wrong?**

P.S. I'm subscribing to the specific chat subscriptions as described in documentation.
