### ISSUE TITLE
/deviceManagement/deviceHealthScripts/{deviceHealthScriptId}/deviceRunStates/{deviceHealthScriptDeviceStateId} returns "No method match route template"

### ISSUE THREAD

**Issue by flo1t** [microsoftgraph/microsoft-graph-docs-contrib#9264]
If you use the id from the value field retrievied via:
`GET https://graph.microsoft.com/beta/deviceManagement/deviceHealthScripts/{deviceHealthScriptId}/deviceRunStates`

and try to run:
`GET https://graph.microsoft.com/beta/deviceManagement/deviceHealthScripts/{deviceHealthScriptId}/deviceRunStates/{deviceHealthScriptDeviceStateId}`

You'll get:
```yaml
{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation/key/navigation/key with http verb GET for request /DeviceFE/StatelessDeviceFEService/deviceManagement/deviceHealthScripts('deviceHealthScriptId')/deviceRunStates('id').",
        "innerError": {
            "date": "timestamp",
            "request-id": "someid",
            "client-request-id": "someotherid"
        }
    }
}
```

It's also not possible to:
`DELETE https://graph.microsoft.com/beta/deviceManagement/deviceHealthScripts/{deviceHealthScriptId}/deviceRunStates/{deviceHealthScriptDeviceStateId}`
(same error)
